# Generated by Django 3.1.5 on 2021-02-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210203_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Загальна вартість'),
        ),
    ]
