# Generated by Django 3.1.5 on 2021-02-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210203_2249'),
    ]

    operations = [
        migrations.RenameModel(

        old_name='Card',
        new_name='Cart',),
    ]
