# Generated by Django 3.1.5 on 2021-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainapp', '0006_auto_20210205_1620'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardProduct',
            new_name='CartProduct',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='card',
            new_name='cart',
        )
    ]
