# Generated by Django 3.1.5 on 2021-02-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210207_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна'),
        ),
    ]
